version: '3.4'

services:

  nginx:
    build:
      context: ./docker/nginx
    restart: on-failure
    volumes:
      - ./website/:/var/www/website/
      - ./docker/nginx/configs/${CONTAINER_ENV}/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/configs/${CONTAINER_ENV}/sites/:/etc/nginx/sites-available/:ro
      - ./docker/shared/data/logs/nginx/:/var/log/nginx/
    # network_mode: host
    ports:
      - "3000:3000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.website.rule=Host(`${TRAEFIK_WEBSITE_HOST}`)
      - traefik.http.routers.website.tls.certresolver=myresolver
      - traefik.http.services.website.loadbalancer.server.port=8083

  builder:
    build:
      context: ./docker/node-cli
      args:
        - TIMEZONE=${TIMEZONE}
        - PUID=${PUID}
        - PGID=${PGID}
        - NODE_VERSION=${NODE_VERSION}
    volumes:
      - ./website/:/var/www/website/
    network_mode: host
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED
    command: bash -c "cd /var/www/website && tail -f"

