version: '3.4'

services:

  traefik:
    image: traefik:v2.4
    # network_mode: host # 80, 443, 8080
    command:
      - --pilot.token=${TRAEFIK_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik/configs/${CONTAINER_ENV}/traefik.yaml:/etc/traefik/traefik.yaml
    ports:
      - 80:80
      - 443:443

  nginx:
    build:
      context: ./docker/nginx
    restart: on-failure
    # network_mode: host # 8083
    volumes:
      - ./website/:/var/www/website/
      - ./docker/nginx/configs/${CONTAINER_ENV}/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/configs/${CONTAINER_ENV}/sites/:/etc/nginx/sites-available/:ro
      - ./docker/shared/data/logs/nginx/:/var/log/nginx/
    labels:
      - traefik.enable=true
      - traefik.http.routers.website.rule=Host(`${TRAEFIK_WEBSITE_HOST}`)
      - traefik.http.routers.website.tls.certresolver=myresolver
      - traefik.http.services.website.loadbalancer.server.port=8083

  # builder:
  #   build:
  #     context: ./docker/node-cli
  #     args:
  #       - TIMEZONE=${TIMEZONE}
  #       - PUID=${PUID}
  #       - PGID=${PGID}
  #       - NODE_VERSION=${NODE_VERSION}
  #   volumes:
  #     - ./website/:/var/www/website/
  #   network_mode: host
  #   environment:
  #     - NODE_TLS_REJECT_UNAUTHORIZED
  #   command: bash -c "cd /var/www/website && tail -f"

