api:
  insecure: true

providers:
  docker:
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: test@example.com
      httpChallenge:
        entryPoint: web
      storage: acme.json
